sudo: false
language: node_js

os:
    - linux

env:
    matrix:
        - TRAVIS_NODE_VERSION="0.10"
        - TRAVIS_NODE_VERSION="0.12"
        - TRAVIS_NODE_VERSION="4"
        - TRAVIS_NODE_VERSION="5"
        - TRAVIS_NODE_VERSION="6"
        - TRAVIS_NODE_VERSION="stable"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libasound2-dev
